core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('', include('main.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/scheduler/', include('scheduler.api.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('scheduler/', include('scheduler.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('', views.mainView),
]

scheduler/api/urls.py
from scheduler.api.views import DayView
from django.urls import path

app_name='scheduler-api'

urlpatterns = [
    path('<str:year>/<str:month>/<str:day>/', DayView.as_view(), name="days"),
]

scheduler/urls.py
from django.urls import path
from . import views

app_name='scheduler'

urlpatterns = [
    path('', views.calendar, name='scheduler'),
    path('<int:pk>/', views.dayDetail, name='dayDetail'),
    path('new/', views.newAppointment, name='newAppointment'),
]

main/models.py
from django.db import models

# Create your models here.

scheduler/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Year(models.Model):
    year = models.IntegerField(default=datetime.datetime.now().year, unique=True)

    def __str__(self):
        return 'Year ' + str(self.year)

class Month(models.Model):
    year = models.ForeignKey(Year, on_delete=models.CASCADE)
    month = models.IntegerField(default=datetime.datetime.now().month)

    def __str__(self):
        return 'Year ' + str(self.year.year) + ', Month ' + str(self.month)

class Day(models.Model):
    month = models.ForeignKey(Month, on_delete=models.CASCADE)
    day = models.IntegerField(default=datetime.datetime.now().day)

    def __str__(self):
        return 'Year ' + str(self.month.year.year) + ', Month ' + str(self.month.month) + ', Day ' + str(self.day)

class Appointment(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    time = models.TimeField()
    duration = models.IntegerField(default=15)
    provider = models.ForeignKey(User, on_delete=models.CASCADE, related_name='provider')
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient')
    topic = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    confirmed = models.BooleanField(default=False)
    arrived = models.BooleanField(default=False)
    chair = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)
    canceled = models.BooleanField(default=False)

    def __str__(self):
        return str(self.day.month.year.year) + '/' + str(self.day.month.month) + '/' + str(self.day.day) + ' (' + str(self.time) + '): ' + self.patient.username + ' ' + self.topic

scheduler/forms.py
from django.forms import ModelForm
from .models import Appointment

class AppointmentForm(ModelForm):
    class Meta:
        model=Appointment
        fields= '__all__'

main/views.py
from django.shortcuts import render

def mainView(request):
    return render(request, 'main/index.html')

scheduler/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth.models import User

from scheduler.api.serializers import YearSerializer, MonthSerializer, DaySerializer, AppointmentSerializer
from scheduler.models import Year, Month, Day, Appointment

class YearView(APIView):

    def get(self, queryset=None, **kwargs):
        year = self.kwargs.get('pk')
        if Year.objects.filter(pk=year).exists():
            year = Year.objects.filter(pk=year)
            serializer = YearSerializer(year)
            print(serializer)
            return Response(data=serializer.data, status=status.HTTP_200_OK)
        else:
            year = Year()
            year.save()
            serializer = YearSerializer(year)
            print(serializer)
            return Response(data=serializer.data, status=status.HTTP_200_OK)

class DayView(APIView):

    def get(self, queryset=None, **kwargs):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        if Year.objects.filter(year=year).exists():
            year = Year.objects.get(year=year)
        else:
            year = Year(year=year)
            year.save()
        if Month.objects.filter(year=year, month=month).exists():
            month = Month.objects.get(year=year, month=month)
        else:
            month = Month(year=year, month=month)
            month.save()
        if Day.objects.filter(month=month, day=day).exists():
            day = Day.objects.get(month=month, day=day)            
        else:
            day = Day(month=month, day=day)
            day.save()
        objects = Appointment.objects.filter(day=day)
        appointments = []
        for i in objects:
            serializer = AppointmentSerializer(i)
            appointments.append(serializer.data)
        return Response(data=appointments, status=status.HTTP_200_OK)
    
    def post(self, request, **kwargs):
        data = request.data[0]
        print(data)
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        day = self.kwargs.get('day')
        if Year.objects.filter(year=year).exists():
            year = Year.objects.get(year=year)
        else:
            year = Year(year=year)
            year.save()
        if Month.objects.filter(year=year, month=month).exists():
            month = Month.objects.get(year=year, month=month)
        else:
            month = Month(year=year, month=month)
            month.save()
        if Day.objects.filter(month=month, day=day).exists():
            day = Day.objects.get(month=month, day=day)           
        else:
            day = Day(month=month, day=day)
            day.save()
        provider = User.objects.get(pk=data['provider'])
        patient = User.objects.get(pk=data['patient'])
        newAppointment = Appointment(day=day, time=data["time"], duration=data["duration"], provider=provider, patient=patient, topic=data['topic'], comment=data['comment'])
        newAppointment.save()
        objects = Appointment.objects.filter(day=day)
        appointments = []
        for i in objects:
            serializer = AppointmentSerializer(i)
            appointments.append(serializer.data)
        return Response(data=appointments, status=status.HTTP_200_OK)

scheduler/views.py
from django.shortcuts import redirect, render

from .forms import AppointmentForm
from .models import Appointment, Day
from datetime import datetime

def calendar(request):
    days = Day.objects.all()
    appointments = Appointment.objects.all()
    content = {'days': days, 'appointments': appointments}
    return render(request, 'scheduler/index.html', content)

def dayDetail(request, pk):
    if Day.objects.filter(date=datetime(2022, 11, pk)).exists():
        day = Day.objects.get(date=datetime(2022, 11, pk))
        print("exist")
    else:
        day = Day(date=datetime(2022, 11, pk))
        print("created", day)
        day.save()
    appointments = Appointment.objects.filter(day=day.pk)
    content = {'day': day, 'appointments': appointments}
    return render(request, 'scheduler/dayDetail.html', content)

def newAppointment(request):
    form = AppointmentForm
    content = {'form': form}
    if request.method == 'POST':
        appointment = form(request.POST)
        if appointment.is_valid():
            appointment.save()
        print(request)
        return redirect('scheduler:dayDetail', 1)
    return render(request, 'scheduler/newAppointment.html', content)

main/templates/main/index.html
HELLO
<a href="{% url 'scheduler:scheduler' %}">Calendar</a>

scheduler/templates/scheduler/dayDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>day</title>
</head>
<body>
    <button><a href="{% url 'scheduler:newAppointment' %}">Nueva</a></button>
    <ul>
    {% for a in appointments %}
        <li>
            <h5>{{ a.patient }}, {{ a.topic }}</h6>
            <p>{{ a.comment }}</p>
            <p>{{ a.provider}}</p>
            <p>{{ a.date}}</p>
        </li>
    {% endfor %}
    </ul>
</body>
</html>

scheduler/templates/scheduler/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'scheduler/css/style.css' %}">
</head>
<body>    
    <div class="calendar">
        <header>
          <h1>November 2022</h1>
        </header>
      
        <ul class="weekdays">
          <li>
            <abbr title="S">Sunday</abbr>
          </li>
          <li>
            <abbr title="M">Monday</abbr>
          </li>
          <li>
            <abbr title="T">Tuesday</abbr>
          </li>
          <li>
            <abbr title="W">Wednesday</abbr>
          </li>
          <li>
            <abbr title="T">Thursday</abbr>
          </li>
          <li>
            <abbr title="F">Friday</abbr>
          </li>
          <li>
            <abbr title="S">Saturday</abbr>
          </li>
        </ul>
      
        <ol class="day-grid">
          <li class="month=prev">29</li>
          <li class="month=prev">30</li>
          <li class="month=prev">31</li>
          <li>
            <a href="{% url 'scheduler:dayDetail' 1 %}">1</a>
          </li>
          <li>2</li>
          <li>3</li>
          <li>4</li>
          <li>5</li>
          <li>6</li>
          <li>7</li>
          <li>8</li>
          <li>9</li>
          <li>10</li>
          <li>11</li>
          <li>12</li>
          <li>13</li>
          <li>14</li>
          <li>15</li>
          <li>16</li>
          <li>17</li>
          <li>18</li>
          <li>19</li>
          <li>20</li>
          <li>21</li>
          <li>22</li>
          <li>23</li>
          <li>24</li>
          <li>25</li>
          <li>26</li>
          <li>27</li>
          <li>28</li>
          <li>29</li>
          <li>30</li>
          <li class="month-next">1</li>
          <li class="month-next">2</li>
        </ol>
    </div>
</body>
</html>

scheduler/templates/scheduler/newAppointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>